FROM node:20.19.3-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install

RUN npm run db:generate

RUN npm run build

CMD ["npm", "run", "start-user-app"]